### ISSUE TITLE
Hybrid Hunter 1.0.8, Install had a problem 

### ISSUE THREAD

**Issue by Canon88** [Security-Onion-Solutions/securityonion-saltstack#48]
**OS: Ubuntu 16.04**

When I install Hybrid Hunter 1.0.8, there is a problem:
Has anybody seen this problem? Please help me, thanks!
I have checked the log, is it THE HIVE error?

![image](https://user-images.githubusercontent.com/19372121/57979172-64472c80-7a4c-11e9-9bd0-a4e2ec43b8d4.png)
**sosetup.log:**
```
----------
          ID: hivescript
    Function: cmd.script
      Result: True
     Comment: Command 'hivescript' run
     Started: 07:25:56.505435
    Duration: 319733.621 ms
     Changes:   
              ----------
              pid:
                  118638
              retcode:
                  0
              stderr:
                  *   Trying 192.168.100.128...
                    % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                                   Dload  Upload   Total   Spent    Left  Speed
                  
                    0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:00:03 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:00:04 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:00:05 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:00:06 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:00:07 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:00:08 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:00:09 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:00:10 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:00:11 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:00:12 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:00:13 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:00:14 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:00:15 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:00:16 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:00:17 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:00:18 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:00:19 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:00:20 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:00:21 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:00:22 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:00:23 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:00:24 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:00:25 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:00:26 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:00:27 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:00:28 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:00:29 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:00:30 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:00:31 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:00:32 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:00:33 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:00:34 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:00:35 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:00:36 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:00:37 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:00:38 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:00:39 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:00:40 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:00:41 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:00:42 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:00:43 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:00:44 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:00:45 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:00:46 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:00:47 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:00:48 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:00:49 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:00:50 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:00:51 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:00:52 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:00:53 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:00:54 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:00:55 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:00:56 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:00:57 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:00:58 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:00:59 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:01:00 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:01:01 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:01:02 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:01:03 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:01:04 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:01:05 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:01:06 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:01:07 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:01:08 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:01:09 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:01:10 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:01:11 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:01:12 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:01:13 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:01:14 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:01:15 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:01:16 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:01:17 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:01:18 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:01:19 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:01:20 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:01:21 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:01:22 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:01:23 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:01:24 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:01:25 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:01:26 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:01:27 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:01:28 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:01:29 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:01:30 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:01:31 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:01:32 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:01:33 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:01:34 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:01:35 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:01:36 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:01:37 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:01:38 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:01:39 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:01:40 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:01:41 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:01:42 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:01:43 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:01:44 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:01:45 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:01:46 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:01:47 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:01:48 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:01:49 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:01:50 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:01:51 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:01:52 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:01:53 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:01:54 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:01:55 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:01:56 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:01:57 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:01:58 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:01:59 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:02:00 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:02:01 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:02:02 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:02:03 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:02:04 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:02:05 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:02:06 --:--:--     0* connect to 192.168.100.128 port 443 failed: Connection timed out
                  * Failed to connect to 192.168.100.128 port 443: Connection timed out
                  * Closing connection 0
                  curl: (7) Failed to connect to 192.168.100.128 port 443: Connection timed out
                  *   Trying 192.168.100.128...
                    % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                                   Dload  Upload   Total   Spent    Left  Speed
                  
                    0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:00:03 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:00:04 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:00:05 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:00:06 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:00:07 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:00:08 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:00:09 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:00:10 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:00:11 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:00:12 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:00:13 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:00:14 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:00:15 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:00:16 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:00:17 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:00:18 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:00:19 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:00:20 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:00:21 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:00:22 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:00:23 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:00:24 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:00:25 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:00:26 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:00:27 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:00:28 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:00:29 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:00:30 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:00:31 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:00:32 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:00:33 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:00:34 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:00:35 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:00:36 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:00:37 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:00:38 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:00:39 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:00:40 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:00:41 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:00:42 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:00:43 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:00:44 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:00:45 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:00:46 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:00:47 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:00:48 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:00:49 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:00:50 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:00:51 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:00:52 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:00:53 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:00:54 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:00:55 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:00:56 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:00:57 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:00:58 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:00:59 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:01:00 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:01:01 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:01:02 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:01:03 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:01:04 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:01:05 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:01:06 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:01:07 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:01:08 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:01:09 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:01:10 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:01:11 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:01:12 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:01:13 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:01:14 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:01:15 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:01:16 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:01:17 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:01:18 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:01:19 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:01:20 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:01:21 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:01:22 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:01:23 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:01:24 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:01:25 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:01:26 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:01:27 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:01:28 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:01:29 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:01:30 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:01:31 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:01:32 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:01:33 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:01:34 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:01:35 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:01:36 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:01:37 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:01:38 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:01:39 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:01:40 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:01:41 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:01:42 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:01:43 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:01:44 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:01:45 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:01:46 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:01:47 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:01:48 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:01:49 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:01:50 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:01:51 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:01:52 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:01:53 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:01:54 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:01:55 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:01:56 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:01:57 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:01:58 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:01:59 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:02:00 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:02:01 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:02:02 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:02:03 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:02:04 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:02:05 --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:--  0:02:06 --:--:--     0* connect to 192.168.100.128 port 443 failed: Connection timed out
                  * Failed to connect to 192.168.100.128 port 443: Connection timed out
                  * Closing connection 0
                  curl: (7) Failed to connect to 192.168.100.128 port 443: Connection timed out
              stdout:

Summary for local
------------
Succeeded: 9 (changed=9)
Failed:    0
------------
Total states run:     9
Total run time: 465.332 s
Enabling checkin at boot
[ERROR   ] Rendering exception occurred
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/utils/templates.py", line 170, in render_tmpl
    output = render_str(tmplstr, context, tmplpath)
  File "/usr/lib/python2.7/dist-packages/salt/utils/templates.py", line 403, in render_jinja_tmpl
    buf=tmplstr)
SaltRenderError: Jinja variable 'dict object' has no attribute u'ubuntu'
[CRITICAL] Rendering SLS 'base:ssl' failed: Jinja variable 'dict object' has no attribute u'ubuntu'
local:
    Data failed to compile:
----------
    Rendering SLS 'base:ssl' failed: Jinja variable 'dict object' has no attribute u'ubuntu'
```

**Comment by TOoSmOotH** [comment]
I believe I answered this on reddit.
